# Numpy 연습
 다음 지시문에 따라 알맞은 결과를 출력하세요.
* 출처: Udemy - Python for Machine Learning & Data Science Masterclass

In [1]:
import numpy as np

**1. 모든 값이 0인 10개 길이를 갖는 배열을 생성하세요.(zeros)**

In [2]:
# 여기는 비워두세요

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**2. 모든 값이 1인 길이 10의 배열을 생성하세요.(ones)**

In [4]:
# 여기는 비워두세요

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**3. 모든 값이 5인 길이 10의 배열을 생성하세요.(full)**

In [5]:
# 여기는 비워두세요

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

**4. 10,11,12...50을 원소로 갖는 배열을 생성하세요.(arange)**

In [8]:
# 여기는 비워두세요

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**5.10부터 50까지 짝수만 갖는 배열을 생성하세요(arange)**

In [9]:
# 여기는 비워두세요

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**6. 0~8을 원소로 갖는 3x3 행렬을 생성하세요(arange, reshape||resize)** 

In [18]:
# 여기는 비워두세요

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**7. 3x3의 단위행렬을 생성하세요.(identity||eye)**

In [19]:
# 여기는 비워두세요

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**8. NumPy로 0과 1사이 난수를 생성하세요(random)**

In [26]:
# 여기는 비워두세요

array([0.10584304])

**9. 표준정규분포로부터 추출된 25개의 난수를 갖는 배열을 생성하세요(randn)**  
아래 결과와 다를 수 있습니다.

In [27]:
# 여기는 비워두세요

array([-0.27651827, -0.56786234, -0.70221147,  0.39443293,  0.15785262,
        0.45183004,  0.26196822, -0.05623809,  0.89794098,  0.06317105,
        0.79940858,  0.7800319 ,  0.19804605,  0.58014365, -1.48432324,
       -0.37999587, -0.4207964 ,  0.05374193, -1.34402334,  0.33720495,
       -0.77636894, -1.06888152,  1.26908312, -0.18543534, -0.49394582])

**10. 다음 배열을 생성하세요.**

In [30]:
# 여기는 비워두세요

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**11. 0과 1사이 균일한 간격을 갖는 길이 20의 배열을 생성하세요.(linspace)**

In [21]:
# 여기는 비워두세요

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection
다음 배열을 토대로 지시문을 수행하세요.

In [23]:
mat = np.arange(1, 26).reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**12. 다음의 결과를 출력하세요.**

In [31]:
# 여기는 비워두세요

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

**13. 다음의 결과를 출력하세요.(인덱스 위치)**

In [24]:
# 여기는 비워두세요

20

**14. 다음의 결과를 출력하세요.**

In [33]:
# 여기는 비워두세요

array([[ 2],
       [ 7],
       [12]])

**15. 다음의 결과를 출력하세요.**

In [34]:
# 여기는 비워두세요

array([21, 22, 23, 24, 25])

**16. 다음의 결과를 출력하세요.**

In [35]:
# 여기는 비워두세요

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

**17. mat의 모든 값을 합하시오.**

In [25]:
# 여기는 비워두세요

325

**18. mat의 표준편차를 구하세요.(std)**

In [36]:
# 여기는 비워두세요

7.211102550927978

**19.mat의 각 열의 합을 구하세요.**

In [37]:
# 여기는 비워두세요

array([55, 60, 65, 70, 75])